spring.application.name=nukkad_App

spring.profiles.active=local

spring.datasource.url=jdbc:mysql://localhost:3306/nukkadapp_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

external.otp.api.url=http://Your-auth-service/api/otp
spring.sql.init.mode=always

auth.host=http://192.168.1.100/auth

auth.otp.url=/api/v1/send/otp
auth.otpVerify.url=/api/v1/verify/otp
auth.validateToken.url=/api/v1/validate/token
auth.userAccountDeactivate.url = /api/v1/make_user_status_inactive

auth.client.name=NUKKAD
auth.client.secret=q3F+hzK1Dnsyv7rQOtkR+DQIJdAlPHBr8AlYQ3ZqvE8=

auth.mock.local=false

image.upload.dir=D:/nukkad/uploads/storekeepers

firebase.credentials.path=${FIREBASE_CREDENTIAL_PATH}
#firebase.credentials.path=classpath:firebase-service-account.json




