spring.application.name=nukkad_App

spring.datasource.url=jdbc:mysql://localhost:3306/nukkadApp_db
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

external.otp.api.url=http://Your-auth-service/api/otp
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema.sql

auth.host=http://localhost:8080

auth.otp.url=${auth.host}/api/auth/otp
